### ISSUE TITLE
An error occurred while sending the request.

### ISSUE THREAD

**Issue by balkarov** [thomasgalliker/PushNotifications.Server#30]
Sometimes I get error when I send multiple (5-10) message to iOS devices. Log is:
```json
{
   "StatusCode":null,
   "TargetSite":"Void MoveNext()",
   "Message":"An error occurred while sending the request.",
   "Data":[
      
   ],
   "InnerException":{
      "TargetSite":"Void ThrowRequestAborted(System.Exception)",
      "StackTrace":"   at System.Net.Http.Http2Connection.ThrowRequestAborted(Exception innerException)
   at System.Net.Http.Http2Connection.Http2Stream.CheckResponseBodyState()
   at System.Net.Http.Http2Connection.Http2Stream.TryEnsureHeaders()
   at System.Net.Http.Http2Connection.Http2Stream.ReadResponseHeadersAsync(CancellationToken cancellationToken)
   at System.Net.Http.Http2Connection.SendAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)",
      "Message":"The request was aborted.",
      "Data":[
         
      ],
      "InnerException":{
         "TargetSite":"Void Throw()",
         "StackTrace":"   at System.Net.Security.SslStream.ReadAsyncInternal[TIOAdapter](TIOAdapter adapter, Memory`1 buffer)
   at System.Net.Http.Http2Connection.ProcessIncomingFramesAsync()",
         "Message":"Unable to read data from the transport connection: An existing connection was forcibly closed by the remote host..",
         "Data":[
            
         ],
         "InnerException":{
            "Message":"An existing connection was forcibly closed by the remote host.",
            "SocketErrorCode":"ConnectionReset",
            "ErrorCode":10054,
            "NativeErrorCode":10054,
            "TargetSite":null,
            "StackTrace":"   at System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.CreateException(SocketError error, Boolean forAsyncThrow)
   at System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.ReceiveAsync(Socket socket, CancellationToken cancellationToken)
   at System.Net.Sockets.Socket.ReceiveAsync(Memory`1 buffer, SocketFlags socketFlags, Boolean fromNetworkStream, CancellationToken cancellationToken)
   at System.Net.Sockets.NetworkStream.ReadAsync(Memory`1 buffer, CancellationToken cancellationToken)
   at System.Net.Security.SslStream.ReadAsyncInternal[TIOAdapter](TIOAdapter adapter, Memory`1 buffer)
   at System.Runtime.CompilerServices.AsyncMethodBuilderCore.Start[TStateMachine](TStateMachine& stateMachine)
   at System.Net.Security.SslStream.ReadAsyncInternal[TIOAdapter](TIOAdapter adapter, Memory`1 buffer)
   at System.Net.Security.SslStream.ReadAsync(Memory`1 buffer, CancellationToken cancellationToken)
   at System.Net.Http.Http2Connection.ProcessIncomingFramesAsync()
   at System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1.AsyncStateMachineBox`1.ExecutionContextCallback(Object s)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1.AsyncStateMachineBox`1.MoveNext(Thread threadPoolThread)
   at System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1.AsyncStateMachineBox`1.MoveNext()
   at System.Threading.Tasks.AwaitTaskContinuation.RunOrScheduleAction(IAsyncStateMachineBox box, Boolean allowInlining)
   at System.Threading.Tasks.Task.RunContinuations(Object continuationObject)
   at System.Threading.Tasks.Task`1.TrySetResult(TResult result)
   at System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1.SetExistingTaskResult(Task`1 task, TResult result)
   at System.Net.Security.SslStream.ReadAsyncInternal[TIOAdapter](TIOAdapter adapter, Memory`1 buffer)
   at System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1.AsyncStateMachineBox`1.ExecutionContextCallback(Object s)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1.AsyncStateMachineBox`1.MoveNext(Thread threadPoolThread)
   at System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1.AsyncStateMachineBox`1.MoveNext()
   at System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.InvokeContinuation(Action`1 continuation, Object state, Boolean forceAsync, Boolean requiresExecutionContextFlow)
   at System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.OnCompleted(SocketAsyncEventArgs _)
   at System.Threading._IOCompletionCallback.PerformIOCompletionCallback(UInt32 errorCode, UInt32 numBytes, NativeOverlapped* pNativeOverlapped)
--- End of stack trace from previous location ---
",
            "Data":[
               
            ],
            "InnerException":null,
            "HelpLink":null,
            "Source":null,
            "HResult":-2147467259
         },
         "HelpLink":null,
         "Source":"System.Private.CoreLib",
         "HResult":-2146232800
      },
      "HelpLink":null,
      "Source":"System.Net.Http",
      "HResult":-2146232800
   },
   "HelpLink":null,
   "Source":"System.Net.Http",
   "HResult":-2146232800
}
```

Myybe you know how to fix it?

**Comment by thomasgalliker** [comment]
Huuh, I never had this error, but I rarely send 100's of push notifications at the same time. Is there any chance I can reproduce this? Does it consistently happen when you send sequentially to multiple clients or did you send the requests in parallel?

**Comment by thomasgalliker** [comment]
I did some tests with 100 parallel requests and it finished successfully after ~3 seconds. 
```            
var stopwatch = Stopwatch.StartNew();
var tasks = Enumerable.Range(0, 100).Select(async i => await SendApnsPushNotification()).ToArray();
await Task.WhenAll(tasks);
var elapsed = stopwatch.Elapsed;
```

**Comment by balkarov** [comment]
@thomasgalliker thank you for your answer. Sorry, but I cannot reproduced it on test, but sometimes see it in production logs. 
If I can reproduce it I will inform you here. Thank you!

**Comment by thomasgalliker** [comment]
I‘ll try to reproduce it. Lets keep this issue open for a while.
